# Generated by Django 5.1.4 on 2024-12-29 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
